# Generated by Django 5.1.1 on 2025-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instructor_bio',
            field=models.TextField(blank=True, help_text='Why do you want to become an instructor?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instructor_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instructor_status',
            field=models.CharField(choices=[('none', 'Not Applied'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
