# Generated by Django 5.2.7 on 2025-10-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF Document'), ('ppt', 'PowerPoint'), ('text', 'Text Content')], max_length=10)),
                ('file_upload', models.FileField(blank=True, help_text='Upload PDF or PPT file', null=True, upload_to='lessons/files/')),
                ('text_content', models.TextField(blank=True, help_text='For text-based lessons')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lesson sequence number')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, default=0)),
                ('is_preview', models.BooleanField(default=False, help_text='Allow preview without enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
